services:
  nao_compre_bot:
    build: .
    container_name: nao_compre_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/data/bot.db
